name: Deploy Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          
      - name: Создание версионной папки
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          mkdir -p v$VERSION
          cp -r ru en index.html v$VERSION/
          
      - name: Публикация
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cp -r release/* .
          git add .
          git commit -m "Deploy v$VERSION"
          git push